module Models exposing (..)

import Layout
import Material
import Material.Color as Color
import RemoteData exposing (WebData)


type alias Model =
    { allSongs : WebData AllSongs
    , mdl : Material.Model
    , layout : Layout.Model
    }


initModel : Model
initModel =
    { allSongs = RemoteData.Loading
    , mdl = Material.model
    , layout = Layout.model
    }



-- semi-automatically generated by http://eeue56.github.io/json-to-elm/


type alias AllSongs =
    { songsByfoot : List SongsByFoot
    }


type alias SongsByFoot =
    { foot : Int
    , songs : List Song
    }


type alias Song =
    { folder : String
    , name : String
    , bpm : String
    , notes : String
    }
